#!/usr/bin/env python3
# This file is placed in the Public Domain.


"loop"


import os
import sys


SKIP = ["env", ".git", "files", "fin"]

def loop(path, txt):
    for fnn in os.listdir(path):
        if fnn in SKIP:
            continue
        if os.path.isdir(fnn):
            print("chdir %s" % fnn)
            os.chdir(fnn)
            popen(txt)
            #ppath = os.path.join(path, fnn)
            #loop(ppath, txt)
            os.chdir("..")


def popen(txt):
    for line in os.popen(txt).readlines():
        print(line.rstrip())
        sys.stdout.flush()


if __name__ == "__main__":
    if not len(sys.argv) >= 3:
        print("loop <dir> <cmd>")
    else:
        loop(sys.argv[1], " ".join(sys.argv[2:]))
